from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
CALIBRATION_JSON = REPO_ROOT / "calibration.json"
HAND_LANDMARKER_MODEL = REPO_ROOT / "hand_landmarker.task"

FINGERTIP_STABILITY_SECONDS = 2.0
FINGERTIP_MAX_DISTANCE_FROM_CORNER_PX = 160.0
FINGERTIP_MAX_STABILITY_RADIUS_PX = 20.0
FINGERTIP_FEED_INTERVAL_MS = 100
FINGERTIP_MAX_MISSING_SECONDS = 0.5
