from pathlib import Path

from throw_detection.inference import default_throw_model_path

PACKAGE_DIR = Path(__file__).resolve().parent
RECORDINGS_DIR = PACKAGE_DIR / "recordings"
DEFAULT_VIDEO = RECORDINGS_DIR / "recording.mp4"

DISPLAY_MAX_SIZE = (960, 540)
MAX_CAMERA_PROBE = 10
TARGET_RECORD_FPS = 30.0
FRAME_WINDOW_SIZE = 3
DIFF_BRIGHTNESS_FACTOR = 5.0
DIFF_THRESH_VALUE = 50
MORPH_KERNEL_SIZE = 4
BALL_CIRCULARITY_MIN = 0.5
BALL_CIRCULARITY_MAX = 1.0
DETECTION_RECT_THICKNESS = 6

POSE_JOINT_RADIUS = 8
POSE_BONE_THICKNESS = 3

THROW_MODEL_PATH = default_throw_model_path()
