from pathlib import Path

from throw_detection.inference import default_throw_model_path

PACKAGE_DIR = Path(__file__).resolve().parent
RECORDINGS_DIR = PACKAGE_DIR / "recordings"
DEFAULT_VIDEO = RECORDINGS_DIR / "recording.mp4"

DISPLAY_MAX_SIZE = (960, 540)
MAX_CAMERA_PROBE = 10
TARGET_RECORD_FPS = 30.0
DIFF_BRIGHTNESS_FACTOR = 10.0
DIFF_THRESH_VALUE = 60
FRAME_DIFF_MORPH_KERNEL_SIZE = 5
MOG2_HISTORY = 300
MOG2_VAR_THRESHOLD = 24
MOG2_DETECT_SHADOWS = True
MOG2_MORPH_KERNEL_SIZE = 6
BALL_CIRCULARITY_MIN = 0.4
BALL_CIRCULARITY_MAX = 1.0
BALL_CONTOUR_MIN_AREA = 150
DETECTION_RECT_THICKNESS = 6

POSE_JOINT_RADIUS = 8
POSE_BONE_THICKNESS = 3

THROW_MODEL_PATH = default_throw_model_path()
