from __future__ import annotations

DROP_STREAK_FRAMES: int = 3
MAX_HORIZONTAL_DELTA_PX: int = 8
POST_BOUNCE_CAPTURE_FRAMES: int = 3
SLOWDOWN_RATIO: float = 0.35
MIN_DOWNWARD_VY: float = 2.0
SYNC_TIMEOUT_FRAMES: int = 90
SYNC_PAIRING_WINDOW_FRAMES: int = 90
SYNC_COOLDOWN_SECONDS: float = 3.0
