from pathlib import Path

from video_viewer.config import DISPLAY_MAX_SIZE, TARGET_RECORD_FPS

PACKAGE_DIR = Path(__file__).resolve().parent
RECORDINGS_DIR = PACKAGE_DIR / "recordings"
LEFT_VIDEO = RECORDINGS_DIR / "left.mp4"
RIGHT_VIDEO = RECORDINGS_DIR / "right.mp4"
GAME_JSON = RECORDINGS_DIR / "game.json"
SETUP_JSON = PACKAGE_DIR / "camera_setup.json"

DISPLAY_MAX_SIZE = DISPLAY_MAX_SIZE
TARGET_FPS = TARGET_RECORD_FPS

# Default camera geometry (meters / degrees).
DEFAULT_MAIN_DISTANCE_M = 1.2
DEFAULT_SECONDARY_DISTANCE_M = 1.5
DEFAULT_MAIN_HEIGHT_M = 0.8
DEFAULT_SECONDARY_HEIGHT_M = 0.9
DEFAULT_CAMERA_ANGLE_DEG = 90.0
DEFAULT_HORIZONTAL_FOV_DEG = 70.0

MAX_TRIANGULATION_HEIGHT_M = 3.0
MAX_TRIANGULATION_RESIDUAL_M = 0.5
