from pathlib import Path

from video_viewer.config import DISPLAY_MAX_SIZE, TARGET_RECORD_FPS, YOLO_BATCH_SIZE

PACKAGE_DIR = Path(__file__).resolve().parent
RECORDINGS_DIR = PACKAGE_DIR / "recordings"
GAMES_DIR = PACKAGE_DIR / "games"
LEFT_VIDEO = RECORDINGS_DIR / "left.mp4"
RIGHT_VIDEO = RECORDINGS_DIR / "right.mp4"
YOLO_INFERENCES = RECORDINGS_DIR / "yolo_inferences.npz"
GRU_INFERENCES = RECORDINGS_DIR / "gru_inferences.npz"
GAME_JSON = GAMES_DIR / "game.json"

DISPLAY_MAX_SIZE = DISPLAY_MAX_SIZE
TARGET_FPS = TARGET_RECORD_FPS

MIN_TRIANGULATION_HEIGHT_M = -3.0
MAX_TRIANGULATION_HEIGHT_M = 3.0
MAX_TRACK_INTERPOLATION_GAP_S = 0.1
GRAVITY_M_S2 = 9.81
